name: 'Typescript type coverage'
description: '📊 Get type coverage of your typescript code'
author: 'kamack38'
inputs:
  tsConfigPath:
    required: false
    description: 'Path to tsconfig.json file'
    default: '.'
  strict:
    required: false
    description: 'Enable strict mode'
    default: 'false'
  debug:
    required: false
    description: 'Enable debug mode'
    default: 'false'
  ignoreFiles:
    required: false
    description: 'Glob pattern with files to ignore (line separated)'
  threshold:
    required: false
    description: 'Type coverage threshold'
    default: '99'
  ignoreCatch:
    required: false
    description: 'Ignore type any for (try-)catch clause variable'
    default: 'false'
  ignoreUnread:
    required: false
    description: 'Allow writes to variables with implicit any types'
    default: 'false'
runs:
  using: 'node16'
  pre: 'setup.js'
  main: 'dist/index.js'

