name: 'Typescript type coverage'
description: '📊 Get type coverage of your typescript code'
author: 'kamack38'
inputs:
  source-root:
    required: false
    description: 'Sorce directory for analysis'
runs:
  using: 'node16'
  main: 'dist/index.js'
